image:
- Visual Studio 2017
skip_tags: true
skip_commits:
  files:
    - .github/*
    - README.md
init:
  - ps: git config --global core.autocrlf true
build_script:
  - ps: cd dotnet-core
  - ps: ./make.ps1 package
